### ISSUE TITLE
Komentarze do profili

### ISSUE THREAD

**Issue by Stanley** [Krakow2016/wolontariusze#10]
Administratorzy serwisu powinni mieć możliwość dodawania komentarzy do dowolnego profilu wolontariusza. Komentarze powinny być widoczne dla innych administratorów, ale niewidoczne dla wszystkich innych użytkowników. Należy zaimplementować niezbędne zmiany po stronie interface-u www oraz po stronie serwera.

**Comment by pkasperczyk** [comment]
Chciałbym się wziąść za to zadanie, natomiast zadania z aktywności zostawić na potem.

**Comment by Stanley** [comment]
Zrobione w https://github.com/Krakow2016/wolontariusze/pull/20. Dzięki @pkasperczyk!
