### ISSUE TITLE
Rejestracja nowych wolontariuszy

### ISSUE THREAD

**Issue by Stanley** [Krakow2016/wolontariusze#11]
Obecnie zgłaszanie wolontariuszy odbywa się poprzez Google Forms. Następnie dane są konwertowane do naszego formatu i zapisywane w bazie danych. Potrzebujemy zastąpić ten proces naszą stroną z naszym formularzem (z dodatkowym polem na hasło), bezpośrednim zapisem danych do bazy danych oraz weryfikacją adresu email. Do zrobienia jest: interface www formularza oraz obsługa danych po stronie serwera.

**Comment by jjaracz** [comment]
Ja mogę się zająć interfacem formularza. Jak rozumiem ma to być jedna strona gdzie będzie się znajdować tylko formularz ? React js, zwykły html czy może jakiś inny system szablonu ?

**Comment by Stanley** [comment]
Super! Tak, to ma być jedna strona, ale weź pod uwagę że komponenty Reactjs które stworzysz na potrzeby tego formularza powinny być możliwe do wykorzystania również gdzie indziej.

**Comment by jjaracz** [comment]
Miałem na myśli tylko frontend, jeszcze node js nie ogarnąłem na takim poziome aby zrobić backend formularza dobrze. Przydałyby się jakieś warsztaty, robiłem takie rzeczy wiele razy ale niestety jeszcze brakuje mi wiedzy jak to się robi w node js. Głównie chodzi mi o zapisywanie do bazy albo tak jak wcześniej mówiłeś do tymczasowych plików.

**Comment by Stanley** [comment]
Możliwość dodawania nowych użytkowników do systemu została ograniczona do adminów w https://github.com/Krakow2016/wolontariusze/commit/8ec12f663786a36c6182faede25eaaacfb55436d.
