### ISSUE TITLE
Aktywności - lista zadań

### ISSUE THREAD

**Issue by pkasperczyk** [Krakow2016/wolontariusze#13]
Staszek zaproponował, żebym wrzucił tutaj na githuba listę zadań do "aktywności", aby każdy mógł zobaczyć i skomentować.

Jest ona obecna pod adresem:
https://docs.google.com/document/d/1o5EIl_94VTETXYY0A6FbRUP2D2CbIy1l6rnybvo0YDY/edit?usp=sharing

Jest tam zadanie:
"Wyświetlenie aktywności pod odpowiednim url",
to zadanie mam zaczęte, zrobione na podstawie kodu Staszka. Chciałbym je dopracować i dać pull requesta.

**Comment by Stanley** [comment]
Dzięki! A mógłbyś z każdego z tych zadań stworzyć issue? Tak będzie łatwiej prowadzić dyskusję.
