### ISSUE TITLE
Aktywności - wyświetlenie aktywności pod odpowiednim url

### ISSUE THREAD

**Issue by pkasperczyk** [Krakow2016/wolontariusze#18]
Jest to utworzenie analogicznej struktury plików jak Staszek zrobił dla wolontariuszy
Tutaj do osiągnięcia jest to, aby dane z testowej listy aktywności były wyświetlane pod odpowiednim adresem. Design w react może być bardzo prosty.

Mam zaczęte

**Comment by pkasperczyk** [comment]
Mam problem z pushowaniem tego na githuba:
Łącząc się po ssh `git push origin activities_part_1` otrzymuję:

```
Enter passphrase for key '/root/.ssh/id_rsa': 
ERROR: Permission to Krakow2016/wolontariusze.git denied to pkasperczyk.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

W origin mam `git@github.com:Krakow2016/wolontariusze.git`

**Comment by wwluk** [comment]
Nie masz uprawnień do tego repozytorium. Musisz zrobić forka (kopię) na swoim koncie i do niego zrobić push, a następnie otworzysz pull-request.
Rób mniej więcej jak tutaj:
https://www.youtube.com/watch?v=YTbRzhQju4c

Jak już będziesz miał forka to do niego pushujesz i otwierasz pull-request. Na swojej maszynie zrobisz tak:
git remote add myFork https://github.com/pkasperczyk/wolontariusze.git
git push myFork master

zmiany pojawią się w https://github.com/pkasperczyk/

**Comment by pkasperczyk** [comment]
dzięki, udało się utworzyć pull request
