### ISSUE TITLE
Obsługa wyboru lokalizacji dla aktywności

### ISSUE THREAD

**Issue by pkasperczyk** [Krakow2016/wolontariusze#27]
Jeśli w zadaniu ma być podana lokalizacja czyli np. "Miasto, Ulica", albo nawet może trzeba przechowywać współrzędne geograficzne.
Jeśli tak, to może warto zrobić wybieranie lokalizacji za pomocą map google? Czy jest to legalne i możliwe?

**Comment by Stanley** [comment]
Mapy Google są płatne z tego co mi wiadomo. Dla nas, tak mi się wydaje, że lepiej się sprawdzi [OpenStreetMap](http://wiki.openstreetmap.org/wiki/List_of_OSM-based_services), gdyż jest darmowa oraz dla Krakowa i okolic jest również dokładniejsza.

**Comment by pkasperczyk** [comment]
Jest to kolejne zadanie, którym chciałbym się zająć. Mam już pewne rzeczy zrobione.

**Comment by Stanley** [comment]
Bierz śmiało :) Ja na razie nie ruszam nic z aktywności.

**Comment by pkasperczyk** [comment]
Do soboty (6 Luty 2016) mam zamiar wystawić pull requesta

**Comment by pkasperczyk** [comment]
Wydaje mi się, że pojawiły się problemy - nie doczytałem licencji:

Jeśli korzystamy z danych open street map, jak np. pozycja geograficzna i dodajemy to do bazy danych to tworzy się `Derivative Database`. Wg tego co czytam, taką bazę danych należy upublicznić.

http://wiki.openstreetmap.org/wiki/Legal_FAQ

Do określenia pozycji geograficznej używam Nominatim, a dzisiaj znalazłem, że tam także nałożone są pewne limity - np. 1 request na sekundę:
http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy

**Comment by pkasperczyk** [comment]
Wg wskazówek na stronie http://wiki.openstreetmap.org/wiki/Open_Data_License/Geocoding_-_Guideline, licencji ODbL (czyli to co trzeba upublicznić) podlegają tylko te dane, które posłużyły do ustalenia pozycji geograficznej, jak i sama pozycja geograficzna. 

Napisano tam, cytat:
"The addresses used as input to Nominatim, as well as the geocoded store locations so computed, together form a derivative database and must be shared under ODbL on request."

**Comment by Stanley** [comment]
Nie zagłębiając się w szczegóły tej licencji to nie ma tam chyba nigdzie informacji że dane mają być dostępne "on-line" tylko "on request". Czyli ja to rozumiem tak, że do czasu kiedy ktoś o nie poprosi to nie musimy nic robić.
