### ISSUE TITLE
Możliwość dodania załączników

### ISSUE THREAD

**Issue by pkasperczyk** [Krakow2016/wolontariusze#29]
Wydaje mi się, że na stronie aktywności moglibyśmy dodać także możliwość umieszczenia załączników, np. plików pdf, doc, obrazów. Pytanie ile będziemy mieć miejsca na dysku?

**Comment by Stanley** [comment]
Miejsce mamy nieograniczone, bo normalnie płacimy za hosting. Pytanie tylko po co nam to? Ja jak mam jakiś plik do przesłania to wysyłam link do Dropboxa. Po co komplikować?

**Comment by pkasperczyk** [comment]
Ok, nie pomyślałem o Dropboxie czy Google Drive - jest to dobry pomysł. Więc raczej nie ma potrzeby dodawać sobie pracy.
