### ISSUE TITLE
Profil wolontariusza

### ISSUE THREAD

**Issue by Stanley** [Krakow2016/wolontariusze#3]
**Jak ma wyglądać profil wolontariusza?**
Zbiór pomysłów i dyskusja nad docelowym wyglądem i działaniem publicznego profilu wolontariusza długoterminowego. Strona będzie widoczna dla wszystkich osób, nie tylko zalogowanych.

**Wytyczne działu wolontariatu**

Ogólne założenia:

> (...) stworzenie miejsca wirtualnego, gdzie widoczne byłoby ile i jakie rzeczy robimy, przygotowując się do ŚDM (co więcej - chciałabym, żeby to zostało po - żeby nie wiązać jakoś bardzo projektu z tym wydarzeniem, bo on jest uniwersalny). Chciałabym, żeby to miejsce była tak "przytulnym" miejscem, że wolontariusze chcieliby do niego wracać.

Profil wolontariusza

> Każdy wolontariusz ma swój profil, nad którym może pracować. Dzisiaj obserwuje się jak ludzie tworzą swoje CV, profile zawodowe. To byłby profil wolontaryjny - co robię, bo lubię, co robię za darmo, nie dla pieniędzy, dla innych. (...) Takie miejsce dostępne byłoby dla osób, które podpiszą umowę o wolontariacie (czyli dla tych którzy będą pracować na rzecz ŚDM więcej niż 30 dni roboczych). Wolontariusz razem z podpisaniem umowy miałby dostęp do konta. (...) Tam podpinałby do swojego profilu konkretną pracę.

**Co musimy ustalić?**
- Jakie dane i w jakiej formie chcemy wyświetlać w profilu wolontariusza? Zdjęcie? Inne informacje?
- Czy i jeżeli tak to w jaki sposób wyświetlamy sposób zaangażowania w wolontariat?
- Jakie inne elementy chcemy tu umieścić? Powiązane profile? Coś innego?
- Jakie odnośniki (wewnętrzne i zewnętrzne) chcemy tu umieścić? Social media?
- Czy i jeżeli tak, to jakie interakcje powinny być dozwolone innym zalogowanym wolontariuszom?
- Czy mamy osoby które chcą zająć się stworzeniem grafiki profilu?

Jak zawsze czekam na wasze pytania, opinie, szkice, przykłady stron o podobnej funkcji itp. Im więcej głosów tym lepiej :wink:.

**Comment by Stanley** [comment]
Witajcie!
Chciałbym poddać dyskusji mój pomysł na profil wolontariusza. Oto on:

![snapshot50](https://cloud.githubusercontent.com/assets/41941/7802462/2735d58a-0336-11e5-8bf3-5ef5e29c2f65.png)

Na profil wolontariusza składają się:
- zdjęcia wolontariusza (najlepiej podczas posługi), idąc za przykładem serwisów społecznościowych, jedno profilowe i drugie jako tło.
- strumień aktywności czyli coś co spowoduje że profil będzie żył, a wolontariusze będą wracać aby go aktualizować. Aktywność to coś co łączy wolontariuszy. Może to być odbyte spotkanie, wykonana praca lub np. zgłoszenie się do jakieś akcji. Wzięcie udziału w niektórych aktywnościach może być nagradzana punktami aby w ten sposób zachęcać do uczestnictwa w nich i wzbudzić rywalizację oraz symbolicznie nagradzać wolontariuszy za ich pracę.

Podczas rejestracji konta wolontariusz odpowiada na ogólnikowe pytania. Odpowiedzi na nie będą później częścią jego publicznego profilu (zatem będą widoczne dla wszystkich). Drugą część profilu wolontariusza tworzą odpowiedzi na bardziej szczegółowe pytania dotyczące jego kwalifikacji i umiejętności które będą widoczne tylko dla koordynatorów wolontariatu, którzy na podstawie tych odpowiedzi sugerują wolontariuszom pracę do wykonania.

**Comment by pkasperczyk** [comment]
Myślę, że pomysł jest ok, zawiera chyba najważniejsze informacje, które możemy zamieścić. W początkowej wersji strony myślę, że to dobra podstawa. Można było by dodać jeszcze informację do jakiej sekcji/grupy wolontariusz należy tj. np. sekcja komunikacji, rejestracji czy logistyki.

Co do strumienia aktywności widzę 3 drogi aktualizacji:
-wolontariusz klika sobie na daną dostępną gdzieś aktywność, że bierze w niej udział
-koordynator dołącza wolontariusza do danej aktywności/zadania po czym aktualizauje się strumień aktywności na jego profilu
-albo wolontariusz aktualizuje swój status, tj. wysyła jakąś wiadomość tekstową

**Comment by Stanley** [comment]
> Można było by dodać jeszcze informację do jakiej sekcji/grupy wolontariusz należy tj. np. sekcja komunikacji, rejestracji czy logistyki.

Dobry pomysł. Z drugiej strony te informacje można by nawet generować automatycznie na podstawie aktywności w których wolontariusz brał udział. Zakładam, że każda aktywność będzie przynależała do jakiejś sekcji.

> -wolontariusz klika sobie na daną dostępną gdzieś aktywność, że bierze w niej udział
> -koordynator dołącza wolontariusza do danej aktywności/zadania po czym aktualizauje się strumień aktywności na jego profilu

Te dwie opcje brałem pod uwagę jednocześnie. Jeżeli dana aktywność będzie tworzona przez koordynatora to pojawi się opcja "dołącz jedynie osoby zaproszone". Inne aktywności nie będą miały takich ograniczeń.

> -albo wolontariusz aktualizuje swój status, tj. wysyła jakąś wiadomość tekstową

Ale żeby nie było nudno to możemy się też zintegrować z serwisami społecznościowymi i zasysać wszystkie wpisy z np. hasztagiem #śdm jako aktywności w profilu.
