### ISSUE TITLE
Integracja z Instagramem

### ISSUE THREAD

**Issue by Stanley** [Krakow2016/wolontariusze#31]
Chcemy aby wolontariusze mogli przypisać do swojego profilu konto na Instagramie, po to żebyśmy mogli wyświetlać na ich profilu zdjęcia z tego konta z hashtagiem #sdm2016. Komunikacja ma odbywać się bezpośrednio z API Instagrama. Dla uproszczenia możemy do tego skorzystać z jakiejś gotowej biblioteki np. https://github.com/stevenschobert/instafeed.js. 

@jjaracz podejmiesz się tego zadania?

**Comment by jjaracz** [comment]
Zrobię to ;)
