### ISSUE TITLE
Zdjęcie profilowe

### ISSUE THREAD

**Issue by Stanley** [Krakow2016/wolontariusze#32]
Chcemy dać możliwość wolontariuszom wgrania własnego zdjęcia profilowego w ustawieniach konta. To samo zdjęcie chcemy wykorzystywać w formie miniaturki na innych podstronach serwisu, dlatego będzie konieczne przygotowanie dwóch zoptymalizowanych rozmiarów tego zdjęcia. Wszystko wgrywamy na Amazon S3 (ponieważ tak będzie najtaniej) i aktualizujemy parametr adresu url zdjęcia profilowego wolontariusza tak samo jak każdy inny atrybut. W związku z tym tworzenie miniatur prawdopodobnie będzie musiało zostać zaimplementowane po stronie przeglądarki w canvas-ie.

**Comment by ppiatek** [comment]
Ja się tym zajmę. Jak będę miał problemy to będę tutaj pisał.

**Comment by Stanley** [comment]
Jakieś postępy @ppiatek ?

**Comment by ppiatek** [comment]
Postaram się wieczorem zrobić pull request. Słabo mi to idzie - dużo mi schodzi czasu na szukaniu powodów, czemu mi coś nie działa po jakiejś zmianie. Będę jutro to ci pokażę. @Stanley

**Comment by ppiatek** [comment]
AWS S3
Lokalizacja: Frankfurt
Jeden bucket (sdm-wolontariusze) na wszystkie zdjęcia wolontariuszy. 
Każdy wolontariusz będzie miał swój folder z różnymi wielkościami zdjęć. W tym momencie będą tworzone 2 zdjęcia. Czy wiadomo może jakie zdjęcia tworzyć? Czy na razie wg uznania?
Nazwa folder: myślałem o formacie "imie-nazwisko-id" - są jakieś sugestie?
@Stanley

**Comment by Stanley** [comment]
Pytasz o rozmiar? Z tego co widzę to jest 375px, ale ze względu na mobile musimy wyświetlać je w rozdzielczości x2, czyli przechowujemy pliki 750x750px. Miniaturki jeszcze nie mają rozmiaru, więc proponuję 100x100px. Nazwa "folderu" wystarczy że będzie `id`.

**Comment by ppiatek** [comment]
Z tego co widzę to są 2 możliwości, które możemy wykorzystać, jeśli chodzi o autoryzację z AWS po stronie klienta. 
1. Wykorzystanie konta Amazon, Facebook, Google lub innego OpenID. Czyli musi ktoś potwierdzić autoryzację logując się na któreś z tych kont.
2. API_KEY i SECRET zaszyte w kodzie i przez to widoczne dla użytkownika. Niezalecane. Chyba, że dane dostępowe ładować tylko dla użytkowników zalogowanych. Ale to musiałoby pewnie być dynamicznie, żeby nie znajdowało się w pliku client.js. Ograniczy to grono osób mogące podejrzeć credentials do AWS tylko do wolontariuszy. 

Łatwiejsza dla wolontariusza i bezpieczniejsza byłaby opcja z autoryzacją po stronie serwera. 

Którą opcję wybrać @Stanley ?

**Comment by Stanley** [comment]
Żadną z tych które przytoczyłeś ;) S3 można skonfigurować tak, żeby dostęp read/write był publiczny: https://aws.amazon.com/articles/5050. Idea jest taka żeby upload odbywał się bez pośrednictwa naszego serwera.

**Comment by ppiatek** [comment]
Ja dzisiaj na spotkaniu nie dam rady być.

Niestety nie udało mi się zamknąć tego tematu z avatarem do dzisiejszego deadline'a. 
Zrobiłem tyle co jest opisane w pull request https://github.com/Krakow2016/wolontariusze/pull/35 

Czy będziesz to ty kończył, czy kontynuować, czyli: 
- poprawa jakości zdjęć
- zmiana credentials zaszytych w kodzie na wysyłanie postem
- zapisanie do bazy danych
- ręczne kadrowanie zdjęcia

Do @Stanley

**Comment by Stanley** [comment]
Dzięki! Zajmę się resztą.

**Comment by ppiatek** [comment]
Czy w takim razie robić coś innego?

**Comment by Stanley** [comment]
Niedługo pojawi się więcej zadań w ramach wydania 2.0 (https://github.com/Krakow2016/wolontariusze/milestones/Wydanie%202.0) Jak znajdziesz coś dla siebie to możesz się zgłosić :)

**Comment by Stanley** [comment]
Zmiana avatara jest już dostępna na gałęzi master. Zamykam.
