### ISSUE TITLE
do poprawy na stronie głównej

### ISSUE THREAD

**Issue by IwonaJ** [Krakow2016/wolontariusze#56]
w stopce na dole jest: Strona została zbudowana przez wolontariuszy **ŚDM w Krakowie w 2016r.**--oficjalna nazwa to **ŚDM KRAKÓW 2016** -- > I na tą oficjalną nazwę trzeba zmienić.

**Comment by jjaracz** [comment]
Od razu to poprawię. Będzie na moim forku janek3.0
