### ISSUE TITLE
 problem z nadawaniem uprawnień administratora

### ISSUE THREAD

**Issue by IwonaJ** [Krakow2016/wolontariusze#57]
Coś tu się podziało-do sprawdzenia, czemu " nie wchodzi" nadawanie uprawnień administratora.
Przedtem po nadaniu praw, ten komunikat znikał i była informacja, że te prawa ma.
Dodatkowo nie wiadomo, czego dokładnie dotyczą umieszczone na dole 2x "czy jesteś pewien?"

**Comment by jjaracz** [comment]
Gotowe, teraz czekamy na merge od Staszka ;)
