### ISSUE TITLE
Warsztaty

### ISSUE THREAD

**Issue by Stanley** [Krakow2016/wolontariusze#6]
Cześć wszystkim!
Nadszedł czas żeby ruszyć z tym projektem dalej do przodu i zacząć angażować nowe osoby. Projekt jest ambitny i jedna osoba nie jest w stanie dostarczyć wszystkiego w czasie do którego ten serwis po prostu musi działać. Właśnie dlatego chciałem wyjść do was z inicjatywą stworzenia warsztatów na których omawialibyśmy kwestie techniczne tego projektu. Na pierwszych spotkaniach ja oczywiście przedstawiłbym to co zostało już zrobione i zrobił wprowadzenie do użytych technologii. Na kolejnych głos zabierałyby inne osoby. Na liście potencjalnych tematów są:
- Wprowadzenie do JavaScript i Node.js (opcjonalnie HTML i CSS)
- Wprowadzenie do React.js
- Tworzenie aplikacji internetowych w Express.js
- Flux i Fluxible czyli bardziej zaawansowany React

Takie spotkania mogły by być nie tylko okazją do poznania się nawzajem ale także okazją dla was żeby przedstawić swoje projekty programistyczne, niekoniecznie związane z ŚDM. Dzięki lepszej znajomości naszych wspólnych możliwości łatwiej będzie nam dysponować tym całym potencjałem :muscle:. Miejscem spotkania były pomieszczenia komitetu ŚDM przy ulicy Kanoniczej 18. Dajcie proszę znać czy jesteście zainteresowani takimi spotkaniami. Jeżeli tak, to którymi z wymienionych tematów najbardziej (a może jakiś inny?) najbardziej pasowałyby wam oraz w jakim terminie i jak często takie spotkania powinny się odbywać, a jeżeli nie jesteście zainteresowani to napiszcie proszę dlaczego nie i jakie inne formy zachęty by was bardziej zainteresowały.

Czekam na wasze odpowiedzi :wink:

**Comment by jjaracz** [comment]
Cześć,
Wszystkie tematy mi odpowiadają ;) Pasuje mi cały następny tydzień oprócz poniedziałku i wtorku po południu. Mam nadzieje, że to będzie dla początkujących w Node.js ?

**Comment by pkasperczyk** [comment]
Mi chyba najbardziej pasowałaby środa od ok. 16:30.

**Comment by Stanley** [comment]
> Mam nadzieje, że to będzie dla początkujących w Node.js ?

Tak, poziom będzie dopasowany do waszych potrzeb, więc jeżeli chcecie wprowadzenie to będzie wprowadzenie.

> Mi chyba najbardziej pasowałaby środa od ok. 16:30.

Ok, to co powiecie na następną środę 17 VI o tej 16:30?

**Comment by starpak1** [comment]
Cześć, jak najbardziej chętnie pasuje.

**Comment by Stanley** [comment]
Ok. W takim razie termin ustalony na środę 17 czerwca o godzinie 16:30. Miejsce też mamy już zarezerwowane (Kanonicza 18).

Zgłaszajcie się proszę na tej stronie: http://www.meetup.com/Krakow2016/events/223182875/
W razie jakichkolwiek zmian wszystko będzie tam publikowane, dlatego jeżeli się tam nie zarejestrujecie, to może was coś ominąć.

Dzięki za zainteresowanie i do zobaczenia w środę!
